# Generated by Django 3.1.5 on 2022-04-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'city'), ('S', 'state'), ('P', 'country/parish')], max_length=1)),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'active'), (-1, 'expired')])),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('discount', models.FloatField(default=0)),
                ('users', models.IntegerField(default=0)),
            ],
        ),
    ]
