# Generated by Django 3.1.5 on 2022-04-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='city',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='country',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='state',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'active'), (-1, 'expired')], default=0),
        ),
    ]
