# Generated by Django 3.1.5 on 2022-04-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20220415_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='city',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='country',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='state',
        ),
    ]
