# Generated by Django 3.1.5 on 2022-05-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20220415_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='shape_file',
            field=models.CharField(default=None, max_length=999, null=True),
        ),
    ]
