# Generated by Django 3.1.5 on 2022-05-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billing_shape_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='billing',
            name='county',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='state',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='type',
            field=models.CharField(choices=[('C', 'city'), ('S', 'state'), ('P', 'county/parish')], max_length=1),
        ),
    ]
