# Generated by Django 3.1.5 on 2022-06-07 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20220513_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
