# Buildspec runs in the build stage of your pipeline.
version: 0.2

phases:
  build:
    commands:
      - VERSION=$(git rev-parse --short HEAD)
      - chmod +x build-and-deploy.sh
      - ./build-and-deploy.sh $VERSION
