version: '3.9'

volumes:
  dbdata:

networks:
  backend:
    driver: bridge

services:
  api:
    restart: always
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/qrisq
    env_file: .env.docker
    container_name: qrisq_api
    depends_on:
      - db
    links:
      - db
    networks:
      - backend

  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=qrisq_db
      - POSTGRES_USER=qrisq
      - POSTGRES_PASSWORD=p@ssw0rd
    container_name: qrisq_db
    hostname: qrisq_psql
    ports:
      - 5430:5432
    volumes:
      - dbdata:/var/lib/postgresql
    networks:
      - backend
