version: '3.9'

volumes:
  dbdata:

networks:
  backend:
    driver: bridge

services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/qrisq
    command: >
      sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: qrisq_alpine_api
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: qrisq_db
    ports:
      - 5430:5432
    volumes:
      - dbdata:/var/lib/postgresql
    networks:
      - backend
