# Generated by Django 3.1.5 on 2022-05-06 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('riskthreat', models.CharField(max_length=255, null=True)),
                ('maxflood', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('maxwind', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('accumrain', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('windrisk', models.CharField(max_length=255, null=True)),
                ('maxwind_dir', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('maxwind_dirname', models.CharField(max_length=255, null=True)),
                ('landfall_location', models.CharField(max_length=255, null=True)),
                ('landfall_datetime', models.DateTimeField(null=True)),
                ('storm_distance', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('maxflood_datetime', models.DateTimeField(null=True)),
                ('maxwind_datetime', models.DateTimeField(null=True)),
                ('landfall_datetime_local_string', models.CharField(max_length=255, null=True)),
                ('maxflood_datetime_local_string', models.CharField(max_length=255, null=True)),
                ('maxwind_datetime_local_string', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'addressstormdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StormAdvisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storm_advisory_id', models.IntegerField()),
                ('year', models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters')])),
                ('tcid', models.CharField(max_length=4, null=True)),
                ('adv', models.CharField(max_length=2, null=True)),
                ('issued_datetime', models.DateTimeField(null=True)),
                ('last_processed_datetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
