FLUIDPAY_RESPONSE = {
    "0": {"status": "Unknown", "msg": "Unknown, please contact support for more information"},
    "99": {"status": "Pending", "msg": "Used in redirect processors prior to payment being received"},
    "100": {"status": "Approved", "msg": "Transaction was successfully approved"},
    "110": {"status": "Approved, Partial approval",
            "msg": "Transaction was successfully approved, but for a lesser amount"},
    "101": {"status": "Approved, pending customer approval",
            "msg": "Transaction is pending customer approval before release"},
    "200": {"status": "Decline",
            "msg": "Generic decline with no additional information provided by the issuer"},
    "201": {"status": "Do not honor",
            "msg": "Generic decline with no additional information provided by the issuer"},
    "202": {"status": "Insufficient funds", "msg": "Declined for insufficient funds"},
    "203": {"status": "Exceeds withdrawl limit", "msg": "Declined for exceeding a withdrawl limit set by the issuer"},
    "204": {"status": "Invalid Transaction", "msg": "Declined as the issuer does not recognize the transaction"},
    "205": {"status": "SCA Decline", "msg": "Soft Decline indicating that a SCA challenge is required"},
    "220": {"status": "Invalid Amount", "msg": "Provided amount is not supported by the issuer"},
    "221": {"status": "No such Issuer", "msg": "The issuing bank can not be found"},
    "222": {"status": "No credit Acct", "msg": "Invalid credit card number"},
    "223": {"status": "Expired Card", "msg": "Credit card as expired and can not be processed"},
    "225": {"status": "Invalid CVC", "msg": "Invalid CVC or CVV2 value has been provided"},
    "226": {"status": "Cannot Verify Pin", "msg": "Card requires PIN"},
    "240": {"status": "Refer to issuer", "msg": "Generic decline by the issuing bank"},
    "250": {"status": "Pick up card (no fraud)", "msg": "Decline where issuer is requesting the merchant hold the card"},
    "251": {"status": "Lost card, pick up (fraud account)",
            "msg": "Decline where issuer is requesting the merchant hold the card"},
    "252": {"status": "Stolen card, pick up (fraud account)",
            "msg": "Decline where issuer is requesting the merchant hold the card"},
    "253": {"status": "Pick up card, special condition",
            "msg": "Decline where issuer is requesting the merchant hold the card"},
    "261": {"status": "Stop recurring", "msg": "Decline requesting recurring be stopped"},
    "262": {"status": "Stop recurring", "msg": "Decline requesting recurring be stopped"},
    "300": {"status": "Gateway Decline", "msg": "Generic Platform decline"},
    "310": {"status": "Gateway Decline - Rule Engine", "msg": "Platform has declined based on a fraud rule"},
    "320": {"status": "Gateway Decline - Chargeback",
            "msg": "The transaction was declined because the previous transaction was charged back"},
    "321": {"status": "Gateway Decline - Stop Fraud",
            "msg": "The transaction was declined because the customer record has been flagged as 'stop_fraud'"},
    "322": {"status": "Gateway Decline - Closed Contact",
            "msg": "The transaction was declined because the customer record has been flagged as 'closed_contact'"},
    "323": {"status": "Gateway Decline - Stop Recurring",
            "msg": "The transaction was declined because the customer record has been flagged as 'stop_recurring'"},
    "400": {"status": "Transaction error returned by processor", "msg": "Generic error returned from the processor"},
    "410": {"status": "Invalid merchant configuration", "msg": "Configuration error returned from the processor"},
    "421": {"status": "Communication error with processor", "msg": "Processor is unreachable"},
    "430": {"status": "Duplicate transaction at processor", "msg": "Processor is seeing this as a duplicate transaction"},
    "440": {"status": "Processor Format error", "msg": "Processor has indicated that there is a formating error"}
}

