# Generated by Django 3.1.5 on 2021-03-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20210325_1002'),
        ('user_app', '0002_userprofile_is_preprocessed'),
    ]

    operations = [
    ]
