# Generated by Django 3.1.5 on 2021-04-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_merge_20210325_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_updated',
            field=models.IntegerField(default=0),
        ),
    ]
