# Generated by Django 3.1.5 on 2021-02-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20210210_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
