# Generated by Django 3.1.5 on 2021-05-20 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_userprofile_address_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters')]),
        ),
    ]
