# Generated by Django 3.1.5 on 2021-05-27 05:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20210520_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPingDragAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_drag_attempt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
