# Generated by Django 3.1.5 on 2021-02-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='price'),
        ),
    ]
