# Generated by Django 3.1.5 on 2021-02-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210211_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.DurationField(verbose_name='duration'),
        ),
    ]
