# Generated by Django 3.1.5 on 2021-02-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210215_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssubscription',
            name='cancelled_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userssubscription',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
