# Generated by Django 3.1.5 on 2021-02-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210211_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.DurationField(blank=True, verbose_name='duration'),
        ),
    ]
