# Generated by Django 3.1.5 on 2021-02-11 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20210211_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='duration'),
        ),
    ]
