# Generated by Django 3.1.5 on 2021-04-16 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20210415_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
