# Generated by Django 3.1.5 on 2021-04-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_userpayment_paid_at'),
        ('subscriptions', '0006_userpayment_price'),
    ]

    operations = [
    ]
