# Generated by Django 3.1.5 on 2021-04-23 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0008_auto_20210421_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_transaction_id', models.CharField(max_length=20, unique=True)),
                ('payment_gateway', models.CharField(choices=[('paypal', 'PayPal'), ('fluidpay', 'FluidPay')], max_length=30)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund', to='subscriptions.userpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='refund', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
