# Generated by Django 3.1.5 on 2021-05-26 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_remove_paymentrefund_refund_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='paid_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='payment_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
