# Generated by Django 3.1.5 on 2021-05-26 08:53

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_paypal_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='SubscriptionPlan',
            name='fluidpay_plan_id',
            field=models.CharField(max_length=60, default=""),
            preserve_default=False,
        )
    ]
