# Generated by Django 3.1.5 on 2021-04-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_userpayment_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='payment_id',
            field=models.CharField(max_length=60, default=""),
        ),
    ]
