# Generated by Django 3.1.5 on 2022-01-10 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_auto_20220105_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='recurring',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='user_subscription',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to='subscriptions.usersubscription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='expires_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='subscription_id',
            field=models.CharField(max_length=60),
        ),
    ]
