# Generated by Django 3.1.5 on 2022-06-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_auto_20220419_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
