# Generated by Django 3.1.5 on 2022-06-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_usersubscription_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='gateway_customer_id',
            field=models.CharField(default='', max_length=90),
        ),
    ]
